language: java

os:
  - linux

jdk:
  - oraclejdk9

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install
  - ./gradlew nodeSetup

install:
  - ./gradlew npmInstall

script:
  - ./gradlew build

