language: java

cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/

os:
  - linux


addons:
  apt:
    packages:
    - npm
    
jdk:
  - oraclejdk9
  
script:
  - ./gradlew build

notifications:
  email: false